### ISSUE TITLE
Webhook failed with status code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by AlphaNimmi** [mollie/laravel-mollie#229] opened 2023-06-30 19:59 UTC
I have called webhook for the payment like this 

        $payment = $mollie->payments->create([
                'amount' => [
                    'value' => $price_to_charge_formatted, 
                    'currency' => 'EUR'
                ],
                'description' => 'Onepayment', 
                'redirectUrl' => site_url('complete_payment'),
                'method' => 'creditcard',
                'metadata' => [
                    'user_id' => $user_id,
                    'no_of_days' => $no_of_days,
                ],
            'webhookUrl' => site_url('mollie_webhook') 

        ]);

And my webhook  public function complete_payment() {

        $api_key = $this->db->where('type', 'mollie')->get('social_keys')->result()[0]->app_id;

        $mollie = new MollieApiClient();
        $mollie->setApiKey($api_key);
        $paymentId = $this->session->userdata('payment_id');
       $payment = $mollie->payments->get($paymentId);
        $status = $payment->status; 
         if ($status === 'paid') {
              .........
              .......... //update code
              ...........
}

}

The code works fine and its updating .but mollie dashboard its showing Webhook failed with status code 500 (Internal Server Error)

Also webhooks works(Webhook called successfully, it took 0.1 seconds) when i commented all code         $mollie = new MollieApiClient();
        $mollie->setApiKey($api_key);.if i comment this code ans enter die it works

**Comment by sandervanhooft** [comment] 2023-07-01 09:35
Hi @AlphaNimmi ,

Can you share the error message with trace from your Laravel logs?

**Comment by AlphaNimmi** [comment] 2023-07-01 12:33
@sandervanhooft  No error is showing in the log
 i need to get the payment status ,so i call         
$payment = $mollie->payments->get($paymentId);
So for initializin mollie I call 
  $mollie = new MollieApiClient();
        $mollie->setApiKey($api_key);
this giving the error

**Comment by sandervanhooft** [comment] 2023-07-03 10:20
Hi @AlphaNimmi ,

1. There's little I can do without an actual error message. With the provided information I am unable to reproduce the issue. My first and only guess would be to look into the line `$paymentId = $this->session->userdata('payment_id');` as I suspect there is no active session available when handling the webhook call.
1. This Laravel package comes with a `mollie()` helper that takes care of wiring up the authentication. Why not use that?

There's not much more I can do without an error message. Closing this for now.

**Closed by sandervanhooft** 2023-07-03 10:20 UTC

**Comment by sandervanhooft** [comment] 2023-07-03 10:22
NB consider grabbing the `$payment_id` from the incoming request (see example [here](https://github.com/mollie/laravel-mollie#a-payment-using-the-mollie-api)).
